### PR TITLE
fixes event editor for nextjs sandbox and adds options editor

### LINKED ISSUE #598: Can't type into event input field
I have the tester playground pulled up so I can fire some test events. However, when I try to type anything into the event input field I get errors like:

Screen Shot 2022-09-19 at 2 34 36 PM

If I highlight the text box, I see:

Screen Shot 2022-09-19 at 2 35 15 PM

Problem presents on both chrome and safari.

### PR DESCRIPTION
**Pull request by chrisradek**
Fixes #598

This PR updates the event editor in our next.js dev example to better handle user input. Previously entering characters would throw an error since the JSON was being parsed on each input event.

This PR also adds a second editor to allow passing in the options to a track/identify call. I found this useful when testing integration overrides.

No changeset needed since there are no user-facing changes in published packages.

### CODE REVIEW

**Review by pooyaj — APPROVED** [review]

**Review by dcow — COMMENTED** [review]
👍🏻

File: examples/with-next-js/pages/index.tsx [hunk 1]
```diff
@@ -84,7 +87,8 @@ export default function Home(): React.ReactElement {
         console.error(err)
         setCtx(undefined)
         setAnalytics(undefined)
-        setEvent({})
+        setEvent('{}')
```
Comment (silesky) [inline examples/with-next-js/pages/index.tsx:90]: Eek

**Review by silesky — APPROVED** [review]
Ooh… two editors now! 👍 thanks.

also, thanks @dcow for reporting.
